feat: fix interactive builds
We use the `wasm32-unknown-wasi-cabal` linker shim from
https://github.com/georgefst/quadris, which fixes interactive build
issues like this:

```
wasm32-unknown-wasi-cabal build all
Build profile: -w ghc-9.14.1 -O2
In order, the following will be built (use -v for more details):
 - hedgehog-1.7 (lib) (requires build)
 - primer-miso-0.8.0.0 (exe:primer-miso) (first run)
 - tasty-hedgehog-1.4.0.2 (lib) (requires build)
 - primer-0.7.2.0 (lib:primer-testlib) (first run)
 - hedgehog-classes-0.2.5.4 (lib) (requires build)
 - primer-benchmark-0.7.2.0 (lib) (first run)
 - primer-api-0.7.2.0 (lib:primer-api-testlib) (first run)
 - primer-0.7.2.0 (lib:primer-hedgehog) (first run)
 - primer-benchmark-0.7.2.0 (test:primer-benchmark-test) (first run)
 - primer-benchmark-0.7.2.0 (bench:primer-benchmark) (first run)
 - primer-api-0.7.2.0 (test:primer-api-test) (first run)
 - primer-api-0.7.2.0 (lib:primer-api-hedgehog) (first run)
 - primer-0.7.2.0 (test:primer-test) (first run)
Starting     hedgehog-1.7 (lib)
Preprocessing executable 'primer-miso' for primer-miso-0.8.0.0...
Building executable 'primer-miso' for primer-miso-0.8.0.0...
<command line>: cannot satisfy -package-id miso-1.9.0.0-2iwfE70Ir6BGugvi4pWu6A
    (use -v for more information)
Building     hedgehog-1.7 (lib)

Failed to build hedgehog-1.7.
Build log ( /Users/dhess/.cache/cabal/logs/ghc-9.14.1/hdghg-1.7-0da76e4a.log
):
Configuring library for hedgehog-1.7...
Preprocessing library for hedgehog-1.7...
Building library for hedgehog-1.7...
<command line>: cannot satisfy -package-id concurrent-output-1.10.21-4mik95bkUE8CPm1JkyCen9
    (use -v for more information)
Error: [Cabal-7125]
Failed to build hedgehog-1.7 (which is required by test:primer-test from primer-0.7.2.0, test:primer-api-test from primer-api-0.7.2.0 and others). See the build log above for details.
Failed to build exe:primer-miso from primer-miso-0.8.0.0.

make: *** [Makefile:27: build-wasm] Error 1
```

Oddly only interactive builds are affected.

Additionally, we:

- provide a `test-wrapper` for Wasm tests in the Nix shell

- restore most Wasm `Makefile` targets from the old `Makefile.wasm32`
  system

- add all Wasm optimizer tools to the Nix shell

- sync up our `index.js` shim with
  https://github.com/georgefst/quadris, mainly to support a local
  browser Wasi shim, to reduce external dependencies

We drop Wasm `repl` and `watch` targets for now until we can sync up
with the latest ecosystem improvements. (These were broken in the old
non-`haskell.nix` Wasm system, anyway.)

Future work will include bundling the frontend distribution with Nix.

Signed-off-by: Drew Hess <src@drewhess.com>